### ISSUE TITLE
Last Version on PGXN is 1.1

### ISSUE THREAD

**Issue by theory** [michelp/pgsodium#25]
Hi there. Would you consider releasing updates of pgsodium on PGXN? The [latest release](https://pgxn.org/dist/pgsodium/) there is currently v1.1.1, and it looks like there have been a few releases since then.

If you'd like to automate releasing it on PGXN and GitHub, [here's how to do it with GitHub Actions](https://justatheory.com/2020/10/release-postgres-extensions-with-github-actions/).

**Comment by michelp** [comment]
Your timing is excellent, I was planning on spending part of this weekend figuring out how to automate a pgxn release with github actions.  Thanks for the link!  Will close this when released.
