### ISSUE TITLE
Where my PGXN Release?

### ISSUE THREAD

**Issue by theory** [michelp/pgsodium#5]
Details [here](http://manager.pgxn.org/howto). Draft `META.json` for you (check the license; "ISC" is not known to PGXN):

``` json
{
   "name": "pgsodium",
   "abstract": "Postgres extension for libsodium functions",
   "description": "pgsodium is a PostgreSQL extension that exposes modern libsodium based cryptographic functions to SQL.",
   "version": "1.0.0",
   "maintainer": [
      "Michel Pelletier <pelletier.michel@gmail.com>"
   ],
   "license": "postgresql",
   "provides": {
      "pgsodium": {
         "abstract": "Postgres extension for libsodium functions",
         "file": "src/pgsodium.h",
         "docfile": "README.md",
         "version": "1.0.0"
      }
   },
   "prereqs": {
      "runtime": {
         "requires": {
            "PostgreSQL": "10.0.0"
         }
      }
   },
   "resources": {
      "bugtracker": {
         "web": "https://github.com/michelp/pgsodium/issues/"
      },
      "repository": {
         "url": "git://github.com/michelp/pgsodium.git",
         "web": "https://github.com/michelp/pgsodium/",
         "type": "git"
      }
   },
   "generated_by": "David E. Wheeler",
   "meta-spec": {
      "version": "1.0.0",
      "url": "https://pgxn.org/meta/spec.txt"
   },
   "tags": [
      "sodium",
      "crypto",
      "cryptography",
      "encryption",
      "random",
      "asymmetric encryption",
      "public key"
   ]
}
```

**Comment by michelp** [comment]
Thanks @theory !  I picked ISC as it's the same as libsodium, but wikipedia says " It is functionally equivalent to the simplified BSD and MIT licenses," so maybe it would make more sense to relicense it now to the functionally equivalent Postgresql license, what do you think @marcmunro ?  As the other contributor you would have to agree.

**Comment by marcmunro** [comment]
On Sun, 2020-06-07 at 13:00 -0700, Michel Pelletier wrote:
> Thanks @theory ! I picked ISC as it's the same as libsodium, but
> wikipedia says " It is functionally equivalent to the simplified BSD
> and MIT licenses," so maybe it would make more sense to relicense it
> now to the functionally equivalent Postgresql license, what do you
> think @marcmunro ? As the other contributor you would have to agree.

I have no problem with either license.

__
Marc

**Comment by michelp** [comment]
1.1.1 is released to pgxn https://manager.pgxn.org/distributions/pgsodium/1.1.1
