### ISSUE TITLE
Postgres crash running tests on latest master

### ISSUE THREAD

**Issue by marcmunro** [michelp/pgsodium#7]
...
ok 32 - secretbox_open session key
ok 33 - secretbox_open session key
ok 34 - sha256
ok 35 - sha512
ok 36 - hmac512 verified
ok 37 - hmac512 not verified
ok 38 - hmac256 verified
ok 39 - hmac256 not verified
psql:test/test.sql:275: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:test/test.sql:275: fatal: connection to server was lost
marc:pgsodium$ 

Command: psql -d test -f test/test.sql 
(database is newly created for the tests)

Postgres version: 
marc:pgsodium$ psql
psql (12.3 (Debian 12.3-1.pgdg90+1))

__
Marc

**Comment by marcmunro** [comment]
Seems to be in the server derived keys stuff.  Commenting out those tests makes the crash go away/

**Comment by michelp** [comment]
fixed by 45e652045c212117516b7b11a5fdf4fd9e101337
